services:
  - type: web
    name: medusa-api
    runtime: node
    plan: free
    branch: main
    rootDir: apps/medusa
    buildCommand: |
      yarn install --immutable
      yarn build
    # IMPORTANT: don't set a fixed PORT; Render injects PORT
    startCommand: |
      echo "Starting Medusa on PORT=$PORT..."
      cd apps/medusa/.medusa/server && yarn install && yarn predeploy && HOST=0.0.0.0 yarn start
    healthCheckPath: /health
    envVars:
      - key: HOST
        value: 0.0.0.0
      ...
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
    buildFilter:
      paths:
        - apps/medusa/**

  - type: web
    name: storefront
    runtime: node
    plan: free
    branch: main
    rootDir: apps/storefront
    buildCommand: |
      yarn install --immutable
      yarn build
    # Let Render's PORT flow through to the server process
    startCommand: |
      echo "Starting Storefront on PORT=$PORT..."
      HOST=0.0.0.0 yarn start
    healthCheckPath: /
    envVars:
      # don't set a PORT here either
      - key: NODE_ENV
        value: production
      - key: MEDUSA_BACKEND_URL
        value: https://<your-medusa-domain>
      ...
    buildFilter:
      paths:
        - apps/storefront/**

  - type: redis
    name: medusa-redis
    plan: free
    ipAllowList: []

databases:
  - name: medusa-db
    plan: free
