# render.yaml
services:
  # --- Medusa API ---
  - type: web
    name: medusa-api
    runtime: node
    plan: free
    branch: main
    rootDir: apps/medusa
    buildCommand: |
      yarn install --immutable
      yarn build
    startCommand: |
      cd .medusa/server && yarn install && yarn predeploy && yarn start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: STORE_CORS
        value: https://<your-storefront-domain>
      - key: ADMIN_CORS
        value: https://<your-medusa-domain>
      - key: AUTH_CORS
        value: https://<your-storefront-domain>,https://<your-medusa-domain>
      - key: MEDUSA_BACKEND_URL
        value: https://<your-medusa-domain>
      - key: ADMIN_BACKEND_URL
        value: https://<your-medusa-domain>
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: medusa-kv
          property: connectionString
      - key: STRIPE_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
    buildFilter:
      paths:
        - apps/medusa/**

  # --- Storefront (Remix) ---
  - type: web
    name: storefront
    runtime: node
    plan: free
    branch: main
    rootDir: apps/storefront
    buildCommand: |
      yarn install --immutable
      yarn build
    startCommand: yarn start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MEDUSA_BACKEND_URL
        value: https://<your-medusa-domain>
      - key: MEDUSA_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    buildFilter:
      paths:
        - apps/storefront/**

# Datastores
databases:
  - name: medusa-db
    plan: free

keyValues:
  - name: medusa-kv
    plan: free
