# nixpacks.toml (repo root)

[phases.setup]
nixPkgs = ["nodejs_22", "bash"]
# prepare Yarn 4 via corepack; fall back to installing corepack if missing
cmds = [
  "node -v",
  "bash -lc 'if command -v corepack >/dev/null 2>&1; then echo corepack ok; else npm i -g corepack; fi'",
  "corepack enable",
  "corepack prepare yarn@4.5.0 --activate",
  "yarn --version"
]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["bash -lc 'cd apps/medusa && yarn build:standalone'"]

[start]
cmd = "bash -lc 'cd apps/medusa && yarn predeploy && yarn start:standalone'"
