# Ensure Node & bash are available for all phases
[phases.setup]
nixPkgs = ["nodejs_22", "bash"]

# Use the vendored Yarn 4 binary instead of corepack
[phases.install]
cmds = [
  # Resolve the vendored Yarn path once and install
  "bash -lc 'set -euo pipefail; YARN=$(ls .yarn/releases/yarn-*.cjs | head -n1); node -v; node \"$YARN\" --version; node \"$YARN\" install --immutable'"
]

# Build ONLY the Medusa app (standalone output to .medusa/server)
[phases.build]
cmds = [
  "bash -lc 'set -euo pipefail; YARN=$(ls .yarn/releases/yarn-*.cjs | head -n1); node \"$YARN\" workspace medusa run build:standalone'"
]

# Start: run DB migrations, then launch the compiled server
[start]
cmd = "bash -lc 'set -euo pipefail; YARN=$(ls .yarn/releases/yarn-*.cjs | head -n1); node \"$YARN\" workspace medusa run predeploy && node \"$YARN\" workspace medusa run start:standalone'"
